workflows:
    food-workflow:
        max_build_duration: 120
        instance_type: windows
        environment:
           groups:
              -keystore_credentials
              -app_store_credentials
           vars:
             GOOGLE_PLAY_TRACK: "beta"   
           flutter: "stable"  
           java: 1.0
         cache:
            cache_path:
               -$HOME/.gradle/caches
               -$FLUTTER_ROOT/.pub-cache
               -$HOME/Library/Caches/Cocopods
               -$CM_BUILD_DIR/node_modules
          triggering:
            events:
               - push     
               - pull_request
               - tag
           branch_patterns
               -pattern: "*"
               include: true
            publishing:
               email:
                  recipients:
                      - grupeshvaibhav123@gmail.com
